version: "3.2"
services:
    app:
      build: ./
      command: npm test #or can be npm run test ?
      volumes:
        - ./:/var/www/app 
      ports:
        - 3000:3000
        - 9229:9229

volumes:
    db_data: {}