name: Github Actions Example

on:
  pull_request:
    types: [opened]
  push:
    branches: 
      - master
      - develop
jobs:
  build:
    name: Running Unit Tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ../../docker-compose.yml
    steps:
    - uses: actions/checkout@v2
    - name: Docker build the app
    - run: docker-compose build
    - name: Run docker tests
    - run: docker-compose run test