name: Github Actions Example

on:
  pull_request:
    types: [opened]
  push:
    branches: 
      - master
      - develop
jobs:
  build:
    name: Running Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Docker build the app
    - run: npm ci
    - run: docker build ./
    - run: npm test